### PR TITLE
WIP: Container build

### PR DESCRIPTION
**Pull request by puremourning**
Build in our own container. Just for info for now.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/llvm/3)

### CODE REVIEW

**Comment by bstaletic** [comment]
*Sigh*... you did run a build... from master, instead of container-build... Let's try again.

**Review by bstaletic — CHANGES_REQUESTED** [review]
Sorry about the horrible mess of the history. The branch was not meant to be public. It had hack after hack to get GHA to upload the archives in pieces due to space restrictions.

That's why I wanted to do this in two PRs - first get the big one sorted out, then rebase and fix things in the small-upload-test branch.

> Reviewed 3 of 8 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/llvm/3#-:-MZsbuG59N_hUKcRmyKU:bhwszi7)* status: all files reviewed, 7 unresolved discussions (waiting on @puremourning)

___
*[package_llvm.py, line 342 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZscaiPAho_SVZ3Bs6i:-MZscaiPAho_SVZ3Bs6j:b-t2m56l) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/package_llvm.py#L342)):*
> ```Python
>                               'the archive will be uploaded to. ' )
> 
>   parser.add_argument( '--base-dir', action='store', help='WOrking dir',
> ```

Typo in `WOrking`.
___
*[.github/workflows/package_llvm.yml, line 16 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsapveDydVNPni56FR:-MZsapveDydVNPni56FS:bx9qed0) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/.github/workflows/package_llvm.yml#L16)):*
> ```YAML
>     runs-on: ubuntu-latest
>     # LLVM takes a _long_ time to build. Set timeout to 8 hours
>     timeout-minutes: 480
> ```

This doesn't work. Limit is 360.
___
*[.github/workflows/package_llvm.yml, line 17 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsavOe15WLNbY-3Cmg:-MZsavOe15WLNbY-3Cmh:bcn39tz) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/.github/workflows/package_llvm.yml#L17)):*
> ```YAML
>     # LLVM takes a _long_ time to build. Set timeout to 8 hours
>     timeout-minutes: 480
>     container: 'youcompleteme/llvm:build'
> ```

Container timed out every time. My version of the workflow finished with ~40 minutes to spare.
___
*[.github/workflows/upload_clang.yml, line 19 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsbGLL35B1v55WVmv9:-MZsbGLL35B1v55WVmvA:byquu61) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/.github/workflows/upload_clang.yml#L19)):*
> ```YAML
>       - uses: actions/setup-python@v2
>         with:
>           python-version: '3.x'
> ```

Do we need this?
___
*[.github/workflows/upload_clang.yml, line 26 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsbAKy5mDWFVrxQlcM:-MZsbAKy5mDWFVrxQlcN:b-db8mkx) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/.github/workflows/upload_clang.yml#L26)):*
> ```YAML
>           GITHUB_USERNAME: ${{ github.actor }}
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>         run: ./upload_clang.py ${{ github.event.inputs.version }} --gh-org bstaletic --no-upload
> ```

`--no-upload`? `--gh-org bstaletic`?

Also, this thing can't run in CI without cleaning up along the way. GHA runs out of space.
___
*[ci/image/Dockerfile, line 19 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsdD2a4T_j47Wyc_m7:-MZsdD2a4T_j47Wyc_m8:besbhg4) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/ci/image/Dockerfile#L19)):*
> ```Dockerfile
>                      python3-pip \
>                      python3-setuptools \
>                      p7zip-full \
> ```

No need for `p8zip-full` for the docker run. It only compiles LLVM and Ubuntu 16.04 `7z` is buggy and unusable for extracting `exe` files.
___
*[ci/image/Dockerfile, line 20 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsdSPPB84M5UB30xXz:-MZsdSPPB84M5UB30xY-:b-u5te4n) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/ci/image/Dockerfile#L20)):*
> ```Dockerfile
>                      python3-setuptools \
>                      p7zip-full \
>                      sudo \
> ```

`sudo`? What for?

**Review by puremourning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/llvm/3)* status: all files reviewed, 7 unresolved discussions (waiting on @bstaletic and @puremourning)

___
*[.github/workflows/package_llvm.yml, line 16 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsapveDydVNPni56FR:-MZsnmH27T60uWfpTn8c:bb7slsv) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/.github/workflows/package_llvm.yml#L16)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This doesn't work. Limit is 360.
</blockquote></details>

yup.
___
*[.github/workflows/package_llvm.yml, line 17 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsavOe15WLNbY-3Cmg:-MZsnZIR-EQpvBxWTT7t:b-2esy37) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/.github/workflows/package_llvm.yml#L17)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Container timed out every time. My version of the workflow finished with ~40 minutes to spare.
</blockquote></details>

Yeh, and the problem was not solved by using this container, so I think we can probably go back to the base ubuntu 16.04 gha and just use the later compiler version from the pap
___
*[.github/workflows/upload_clang.yml, line 19 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsbGLL35B1v55WVmv9:-MZsno9J1kgbwcDJOPCm:beoud9h) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/.github/workflows/upload_clang.yml#L19)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

I never tried this workflow. I just ran it manually, but yeah we do need python3 at least.
___
*[.github/workflows/upload_clang.yml, line 26 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsbAKy5mDWFVrxQlcM:-MZsnuwcADmNHhRI3Vnw:b-42eizg) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/.github/workflows/upload_clang.yml#L26)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

`--no-upload`? `--gh-org bstaletic`?

Also, this thing can't run in CI without cleaning up along the way. GHA runs out of space.
</blockquote></details>

right, we can easily clear the tmp dir after each platform is done. should be v. easy.
___
*[ci/image/Dockerfile, line 19 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsdD2a4T_j47Wyc_m7:-MZso8eV2tWPDHKGvVK8:bi2dr64) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/ci/image/Dockerfile#L19)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

No need for `p8zip-full` for the docker run. It only compiles LLVM and Ubuntu 16.04 `7z` is buggy and unusable for extracting `exe` files.
</blockquote></details>

yeah, we can drop this, I kept it as a reminder of what's required, but then I updated the comment.
___
*[ci/image/Dockerfile, line 20 at r3](https://reviewable.io/reviews/ycm-core/llvm/3#-MZsdSPPB84M5UB30xXz:-MZso6oIEAC4hZEdllhL:b-4v6bnu) ([raw file](https://github.com/ycm-core/llvm/blob/959cd6e4722cfed4a85b367cd5da4afe29d777c6/ci/image/Dockerfile#L20)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

`sudo`? What for?
</blockquote></details>

copy/paste from other containers

**Review by puremourning — COMMENTED** [review]
I just wanted to get the uploads done with minimal fuss. This repo is pure admin anyway, so I'm not worried about it being a bit WIP at all times.

We usually have about a year between releases anyway :)

> *[Reviewable](https://reviewable.io/reviews/ycm-core/llvm/3#-:-MZsoKFbEh8tRSjIV-BB:b-iqsw1a)* status: all files reviewed, 7 unresolved discussions (waiting on @bstaletic and @puremourning)

**Pull request closed without merging**
