### PR TITLE
Update the script for LLVM11

### PR DESCRIPTION
**Pull request by bstaletic**
Preparations for the, now released, LLVM11.

For LLVM10, all these changes were only local to my machine and I don't want to redo it every time.

---
This change is [Reviewable](https://reviewable.io/reviews/ycm-core/llvm/1)

### CODE REVIEW

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/llvm/1)* status: all files reviewed, 1 unresolved discussion (waiting on @bstaletic)

___
*[package_llvm.py, line 342 at r1](https://reviewable.io/reviews/ycm-core/llvm/1#-MJSR-8uAHRMs7_SI_fc:-MJSR-8uAHRMs7_SI_fd:b-nhq9md) ([raw file](https://github.com/ycm-core/llvm/blob/985855d430d609cc9497c068f026aec418fad4a8/package_llvm.py#L342)):*
> ```Python
>                               'variable: GITHUB_TOKEN.' )
>   parser.add_argument( '--gh-repo', action='store',
>                        help = 'GitHub api token. Defaults to environment '
> ```

can we fix this comment ?

Can we default this to something ? It wasn't obvious to me what this should be set to

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/llvm/1)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic)

___
*[package_llvm.py, line 253 at r1](https://reviewable.io/reviews/ycm-core/llvm/1#-MJSRyAGCphk9Kt0EAkc:-MJSRyAGCphk9Kt0EAkd:bqxrjt4) ([raw file](https://github.com/ycm-core/llvm/blob/985855d430d609cc9497c068f026aec418fad4a8/package_llvm.py#L253)):*
> ```Python
> def UploadLlvm( args, bundle_path ):
>   response = requests.get(
>     GITHUB_RELEASES_URL.format( owner = args.gh_repo, repo = 'llvm' ),
> ```

this seems odd, should it really be `gh_org` ?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ycm-core/llvm/1)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @puremourning)

___
*[package_llvm.py, line 253 at r1](https://reviewable.io/reviews/ycm-core/llvm/1#-MJSRyAGCphk9Kt0EAkc:-MJScHNI51Sd2J6Nz9l1:b-896fix) ([raw file](https://github.com/ycm-core/llvm/blob/985855d430d609cc9497c068f026aec418fad4a8/package_llvm.py#L253)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

this seems odd, should it really be `gh_org` ?
</blockquote></details>

Done.
___
*[package_llvm.py, line 342 at r1](https://reviewable.io/reviews/ycm-core/llvm/1#-MJSR-8uAHRMs7_SI_fc:-MJSchig0kKjI4KX7n01:b-896fix) ([raw file](https://github.com/ycm-core/llvm/blob/985855d430d609cc9497c068f026aec418fad4a8/package_llvm.py#L342)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

can we fix this comment ?

Can we default this to something ? It wasn't obvious to me what this should be set to
</blockquote></details>

Done.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ycm-core/llvm/1#-:-MJSrKLk5pKGp1mzjMOM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
